<?php

namespace AppBundle\Repository;

/**
 * HorseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HorseRepository extends \Doctrine\ORM\EntityRepository
{
}
