<?php

namespace AppBundle\Repository;

/**
 * StableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StableRepository extends \Doctrine\ORM\EntityRepository
{
}
